# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('result', models.IntegerField(choices=[(1, 'Player1'), (2, 'Player2'), (0, 'Draw')])),
                ('date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('card_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('elo_rating', models.IntegerField(db_index=True, default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('result', models.IntegerField(choices=[(1, 'Player1'), (2, 'Player2'), (0, 'Draw')])),
                ('player1', models.IntegerField(choices=[(1, ''), (2, 'V'), (3, 'CA'), (4, 'EX'), (5, 'C'), (6, 'P'), (7, 'T'), (8, 'D')])),
                ('player2', models.IntegerField(choices=[(1, ''), (2, 'V'), (3, 'CA'), (4, 'EX'), (5, 'C'), (6, 'P'), (7, 'T'), (8, 'D')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_first_player', to='ranking.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_second_player', to='ranking.Player'),
        ),
    ]
