# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_rating_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_rating_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerresults',
            name='max_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerresults',
            name='min_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='placement_games',
            field=models.IntegerField(default=15),
        ),
    ]
