# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_rating_change_and_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_character',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_character',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
